name: excelapp
description: The Official App of the tech fest of Govt. Model Engineering College.
version: 1.0.0+15

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.2
  # Add packages below -- App size is a concern

  # Backend
  path: ^1.7.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  connectivity_plus:
  intl: ^0.17.0
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  social_share: ^2.0.5
 
  # UI
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  # searchable_dropdown: ^1.1.3
  url_launcher: ^6.1.6
  carousel_slider: ^4.1.1
  introduction_screen: ^3.0.2
  font_awesome_flutter: ^10.2.1
  image_picker: ^0.8.6
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true

  assets:
  - assets/BG 2.jpg
  - assets/divider.png
  - assets/excel logo.png
  - assets/categories/
  - assets/introScreen/page2.png
  - assets/introScreen/page3.png
  - assets/introScreen/page4.png
  - assets/icons/
  - assets/devs/
  - assets/discover/
  # - assets/campusAmbassador/refer.png
  # - assets/campusAmbassador/higher.png

  fonts:
      - family: poppins
        fonts:
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold.ttf
            weight: 700
          # - asset: assets/fonts/Poppins-ExtraBold.ttf
          #   weight: 800
      - family: quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Regular.ttf
          # - asset: assets/fonts/Quicksand-SemiBold.ttf
          #   weight: 600
          # - asset: assets/fonts/Quicksand-Bold.ttf
          #   weight: 700
          # - asset: assets/fonts/Quicksand-Light.ttf
          #   weight: 300
