name: excelapp
description: The Official App of the tech fest of Govt. Model Engineering College.
version: 1.0.0+15

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^0.1.2
  # Add packages below -- App size is a concern

  # Backend
  path: ^1.8.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  connectivity_plus: ^3.0.0
  intl: ^0.18.0
  google_sign_in: ^5.4.4
  hive: ^2.2.3
  social_share: ^2.3.1
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^9.3.2
 
  # UI
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.6
  carousel_slider: ^4.1.1
  introduction_screen: ^3.1.4
  font_awesome_flutter: ^10.2.1
  image_picker: ^0.8.6
  fluttertoast: ^8.1.2
  flutter_launcher_icons: ^0.11.0
  provider:
  http: ^0.13.5
  searchable_paginated_dropdown: ^0.0.7
  flutter_html: ^0.11.1
  firebase_core: ^2.5.0
  qr_flutter: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/excellogo.png"
  adaptive_icon_background: "assets/appicon/whitebg.png"
  adaptive_icon_foreground: "assets/appicon/excelicon.png"

flutter:

  uses-material-design: true

  assets:
  - assets/BG 2.jpg
  - assets/qrcode.png
  - assets/divider_design.png
  - assets/excel logo.png
  - assets/Tom ser.jpg
  - assets/excellogo.png
  - assets/categories/
  - assets/introScreen/page2.png
  - assets/introScreen/page3.png
  - assets/introScreen/page4.png
  - assets/icons/
  - assets/appicon/
  - assets/eventicons/
  - assets/devs/
  - assets/discover/
  - assets/events/
  - assets/sampleposter.png
  - assets/MapsicleMap.png
  # - assets/campusAmbassador/refer.png
  # - assets/campusAmbassador/higher.png

  fonts:
      # - family: poppins
      #   fonts:
      #     - asset: assets/fonts/Poppins-Regular.ttf
      #     - asset: assets/fonts/Poppins-SemiBold.ttf
      #       weight: 600
      #     - asset: assets/fonts/Poppins-Bold.ttf
      #       weight: 700
      #     # - asset: assets/fonts/Poppins-ExtraBold.ttf
      #     #   weight: 800
      - family: mulish
        fonts:
          - asset: assets/fonts/Mulish-Regular.ttf
          - asset: assets/fonts/Mulish-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Mulish-Bold.ttf
            weight: 700
      # - family: quicksand
      #   fonts:
      #     - asset: assets/fonts/Quicksand-Regular.ttf
      #     # - asset: assets/fonts/Quicksand-SemiBold.ttf
      #     #   weight: 600
      #     # - asset: assets/fonts/Quicksand-Bold.ttf
      #     #   weight: 700
      #     # - asset: assets/fonts/Quicksand-Light.ttf
      #     #   weight: 300
